// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: aviation.proto

package types

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FilterType int32

const (
	FilterType_UNKNOWN  FilterType = 0
	FilterType_N_NUMBER FilterType = 1
	FilterType_MAKE     FilterType = 2
	FilterType_MODEL    FilterType = 3
	FilterType_AIRLINE  FilterType = 4
)

// Enum value maps for FilterType.
var (
	FilterType_name = map[int32]string{
		0: "UNKNOWN",
		1: "N_NUMBER",
		2: "MAKE",
		3: "MODEL",
		4: "AIRLINE",
	}
	FilterType_value = map[string]int32{
		"UNKNOWN":  0,
		"N_NUMBER": 1,
		"MAKE":     2,
		"MODEL":    3,
		"AIRLINE":  4,
	}
)

func (x FilterType) Enum() *FilterType {
	p := new(FilterType)
	*p = x
	return p
}

func (x FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_aviation_proto_enumTypes[0].Descriptor()
}

func (FilterType) Type() protoreflect.EnumType {
	return &file_aviation_proto_enumTypes[0]
}

func (x FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterType.Descriptor instead.
func (FilterType) EnumDescriptor() ([]byte, []int) {
	return file_aviation_proto_rawDescGZIP(), []int{0}
}

type ListSuggestionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requested string   `protobuf:"bytes,1,opt,name=requested,proto3" json:"requested,omitempty"`
	Existing  []string `protobuf:"bytes,2,rep,name=existing,proto3" json:"existing,omitempty"`
	Size      int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ListSuggestionsRequest) Reset() {
	*x = ListSuggestionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aviation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSuggestionsRequest) ProtoMessage() {}

func (x *ListSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*ListSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_aviation_proto_rawDescGZIP(), []int{0}
}

func (x *ListSuggestionsRequest) GetRequested() string {
	if x != nil {
		return x.Requested
	}
	return ""
}

func (x *ListSuggestionsRequest) GetExisting() []string {
	if x != nil {
		return x.Existing
	}
	return nil
}

func (x *ListSuggestionsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListSuggestionsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        FilterType `protobuf:"varint,1,opt,name=type,proto3,enum=types.FilterType" json:"type,omitempty"`
	Suggestions []string   `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	Size        int32      `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ListSuggestionsReply) Reset() {
	*x = ListSuggestionsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aviation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSuggestionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSuggestionsReply) ProtoMessage() {}

func (x *ListSuggestionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_aviation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSuggestionsReply.ProtoReflect.Descriptor instead.
func (*ListSuggestionsReply) Descriptor() ([]byte, []int) {
	return file_aviation_proto_rawDescGZIP(), []int{1}
}

func (x *ListSuggestionsReply) GetType() FilterType {
	if x != nil {
		return x.Type
	}
	return FilterType_UNKNOWN
}

func (x *ListSuggestionsReply) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *ListSuggestionsReply) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_aviation_proto protoreflect.FileDescriptor

var file_aviation_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x67,
	0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x73, 0x0a,
	0x14, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x2a, 0x49, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x4e, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d,
	0x41, 0x4b, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x10, 0x03,
	0x12, 0x0b, 0x0a, 0x07, 0x41, 0x49, 0x52, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x04, 0x32, 0x7b, 0x0a,
	0x11, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x66, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aviation_proto_rawDescOnce sync.Once
	file_aviation_proto_rawDescData = file_aviation_proto_rawDesc
)

func file_aviation_proto_rawDescGZIP() []byte {
	file_aviation_proto_rawDescOnce.Do(func() {
		file_aviation_proto_rawDescData = protoimpl.X.CompressGZIP(file_aviation_proto_rawDescData)
	})
	return file_aviation_proto_rawDescData
}

var file_aviation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aviation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aviation_proto_goTypes = []interface{}{
	(FilterType)(0),                // 0: types.FilterType
	(*ListSuggestionsRequest)(nil), // 1: types.ListSuggestionsRequest
	(*ListSuggestionsReply)(nil),   // 2: types.ListSuggestionsReply
}
var file_aviation_proto_depIdxs = []int32{
	0, // 0: types.ListSuggestionsReply.type:type_name -> types.FilterType
	1, // 1: types.SuggestionService.ListSuggestions:input_type -> types.ListSuggestionsRequest
	2, // 2: types.SuggestionService.ListSuggestions:output_type -> types.ListSuggestionsReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aviation_proto_init() }
func file_aviation_proto_init() {
	if File_aviation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aviation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSuggestionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aviation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSuggestionsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aviation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aviation_proto_goTypes,
		DependencyIndexes: file_aviation_proto_depIdxs,
		EnumInfos:         file_aviation_proto_enumTypes,
		MessageInfos:      file_aviation_proto_msgTypes,
	}.Build()
	File_aviation_proto = out.File
	file_aviation_proto_rawDesc = nil
	file_aviation_proto_goTypes = nil
	file_aviation_proto_depIdxs = nil
}
