name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.12
      id: go
    - name: checkout
      uses: actions/checkout@v2
    - name: build download
      run: cd download && go build ./...
    - name: build load
      run: cd load && go build ./...
    - name: deploy
      run: RDS_USERNAME=${{ secrets.RDS_USERNAME }} RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} RDS_ENDPOINT=${{ secrets.RDS_ENDPOINT }} make deploy
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
