name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
      id: go
    - name: checkout
      uses: actions/checkout@v2
    - name: build download
      run: cd download && GOARCH=amd64 GOOS=linux go build -o bootstrap ./... && zip -FS bootstrap.zip bootstrap
    # - name: build load
    #   run: cd load && go build ./...
    # - name: build query
      # run: cd query && go build ./...
    - name: deploy
      run: make deploy
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
        RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
        RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
    # - name: node
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: v14.5.0
    # - name: build ui
    #   run: cd ui && npm i && npm run build
    # - name: deploy website
    #   run: make ui
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_DEFAULT_REGION: us-west-2